version: "3"
services:
    tnc-server:
        build: dockerized-tnc-server/
        image: tnc-server:latest
        restart: unless-stopped
        expose:
            - 6700/tcp
        ports:
            - ${TNC_LISTEN_PORT}:6700
        devices:
            - ${TNC_SERIAL}:/dev/ttyTNC0
        environment:
            - BAUDRATE=${TNC_BAUD}

    aprs-bot:
        build: aprs-bot/
        image: aprs-bot:latest
        restart: unless-stopped
        environment:
            - APRS_BOT_ENABLED
            - DEBUG
            - KISS_CONN_TYPE
            - KISS_HOST
            - KISS_PORT
            - MQTT_TOPIC_PREFIX
            - MQTT_PORT
            - MQTT_SERVER